### ISSUE TITLE
Usability issue: `versionCheck` doesn't show the problems it found

### ISSUE THREAD

**Issue by SethTisue** [scalacenter/sbt-version-policy#126]
I have hit this repeatedly in multiple repos over the past year or two – only getting around to reporting it now.

When `versionPolicyCheck` fails, I get the usual MiMa output showing me what the actual problems are.

But when `versionCheck` (the one you run at release time, rather than during PR validation) fails, I don't get any details, I just get e.g.

```
sbt:root> parserCombinatorsJVM / versionCheck
[error] Module scala-parser-combinators has an invalid version number: 1.1.3-RC1. You must increment the minor version number to publish a source incompatible release.
[error] (parserCombinatorsJVM / versionCheck) Module scala-parser-combinators has an invalid version number: 1.1.3-RC1. You must increment the minor version number to publish a source incompatible release.
```

according to the repo readme here,

> MiMa can only detect binary incompatibilities. To detect source incompatibilities, this plugin uses MiMa in forward mode as an approximation. This is not always correct and may lead to false positives or false negatives. This is a known limitation of the current implementation.

I'm suggesting change the plugin so that the specific incompatibilities found are printed.

but it'd also be okay if I need to run an extra command in order to "use MiMa in forward mode" and see the errors, as long as we document what that command is

**Comment by SethTisue** [comment]
looks like I can get the errors by doing `set mimaCheckDirection := "forward"` followed by `mimaReportBinaryIssues`

**Comment by SethTisue** [comment]
Gah. In the repo I'm working on (scala-parser-combinators), that worked to show some errors, but even after I made them go away, `versionCheck` is still failing:

```
sbt:root> show parserCombinatorsJVM/mimaCheckDirection
[info] backward
sbt:root> parserCombinatorsJVM/mimaReportBinaryIssues
[success] Total time: 0 s, completed May 13, 2022, 4:37:13 PM
sbt:root> set parserCombinatorsJVM/mimaCheckDirection := "forward"
sbt:root> parserCombinatorsJVM/mimaReportBinaryIssues
[success] Total time: 0 s, completed May 13, 2022, 4:37:21 PM
sbt:root> parserCombinatorsJVM/versionCheck
[error] Module scala-parser-combinators has an invalid version number: 1.1.2+29-6e3da8f3-SNAPSHOT. You must increment the minor version number to publish a source incompatible release.
[error] (parserCombinatorsJVM / versionCheck) Module scala-parser-combinators has an invalid version number: 1.1.2+29-6e3da8f3-SNAPSHOT. You must increment the minor version number to publish a source incompatible release.
[error] Total time: 0 s, completed May 13, 2022, 4:37:35 PM
```

🙀

**Comment by SethTisue** [comment]
gah, never mind, I misunderstood. the check isn't failing because MiMa is failing — MiMa isn't even running!

rather, it's failing because my `build.sbt` had `Compatibility.BinaryCompatible` but I was trying to release a patch version anyway.

I don't know if I _like_ this design, but at least I understand what's going on.

**Comment by nafg** [comment]
In Slick, I took the opposite approach, which is to compute the version from `versionPolicyIntention` and git tags. (See https://github.com/slick/slick/blob/main/project/Versioning.scala)

The downside of computing `versionPolicyIntention` from `version` is then you have to answer how is `version` specified. You still have to keep updating that. If I have to update one I'd rather it be `versionPolicyIntention` because:
 - Fewer information bits to deal with. It's a choice of only 3 options to choose from; the rest can be inferred. In fact you could keep all 3 versions in place with 2 of the 3 commented at any given time, so updating it is just changing which line is uncommented
 - It's the bit of information that's missing from the computer's perspective, that needs a human to supply it. The version on the other hand is just counting; that computers can do fine when given the exact rules.
 - It may need changing less often, since you don't have to deal with adding and removing `-SNAPSHOT`
 - It's less of a contradiction to sbt-dynver. In fact Slick uses sbt-dynver, and I achieve this by customizing it. sbt-dynver expects to infer the version from git tags, but can you automate creating git tags? If the version can be computed from past tags plus `versionPolicyIntention` then sure! And if your version is explicitly set then you can too, but then you aren't really using sbt-dynver.

In theory, one could have `versionPolicyIntention` inferred too, from metadata in commits. For instance in one project of mine, I prefix commit messages with `^`, `*`, or `+` to indicate the respective version segment it would bump, if any. I then have a release script that computes a git tag to create based on that.

**Comment by julienrf** [comment]
> I don't know if I _like_ this design, but at least I _understand_ what's going on, now. I was baffled/confused before.

I agree that this is can be confusing.

The reason why we did that is because we wanted to support as many use cases as possible.

With a typical setup with `sbt-dynver`, the `versionPolicyIntention` can _not_ be computed from the `version` because it looks like `1.2.3+42-1234abcd` (unless you push a tag, but this is never the case when you submit a PR, for instance), where `1.2.3` is the last published version. So, `sbt-dynver` never bumps the patch, minor, or major version, it only appends metadata to the last published version.

We could decide to support `sbt-release` only, and in this case we would not have had to introduce the `versionPolicyIntention` at all, since with `sbt-release` the version is managed manually (we could derive `versionPolicyIntention` from it). That being said, I think we should support the `sbt-dynver` setup because I believe it’s quite pervasive (especially because of `sbt-ci-release`).

I hope this clarifies things.

**Comment by SethTisue** [comment]
it does, though in 6 months I'll probably have forgotten it and confuse myself all over again :-)

**Comment by SethTisue** [comment]
the poor error message bit Lukas today over at https://github.com/scala/scala-xml/issues/685#issuecomment-1635833645

**Comment by SethTisue** [comment]
Julien asks, over on the scala-xml ticket:

> Do you have suggestions for a better error message?

The main thing would be for `versionCheck` to show me the actual MiMa problems it found, as in the original title of this ticket. (Perhaps I shouldn't have closed this ticket — feel free to reopen.) Without that, it isn't even clear that there _are_ any MiMa failures involved...!

Additionally, it would be helpful if the error message showed the `versionPolicyIntention` and the old and new version numbers, to help the user sanity-checking that the values they are intended are the values being used.

at present, we see e.g.

> [error] Module scala-xml has an invalid version number: 1.3.1. You must increment the minor version number to publish a source incompatible release.

How about something more like:

> [error] Module scala-xml has a version number (now 1.3.1, previously 1.3.0) inconsistent with its declared `versionPolicyIntention` of `BinaryCompatible`. This intention implies that the minor version number should be incremented.

**Comment by SethTisue** [comment]
oh, I basically already said this above:

> I'm suggesting change the plugin so that the specific incompatibilities found are printed.

> but it'd also be okay if I need to run an extra command in order to "use MiMa in forward mode" and see the errors, as long as we document what that command is
