### ISSUE TITLE
Intermodule dependency on `-SNAPSHOT` qualifier conflicts with `BinaryAndSourceCompatibility` setting

### ISSUE THREAD

**Issue by seigert** [scalacenter/sbt-version-policy#155]
We have a project with two modules: `api, client.dependsOn(api)`. They share same version setting: `ThisBuild / version := "1.2.1-SNAPSHOT"`.

If we use `BinaryAndSourceCompatible` compatibility settings we get following error on `versionPolicyCheck`:

```console
[error] Incompatibilities with dependencies of client:1.2.0
[error]   api_2.13: incompatible version change from 1.2.0 to 1.2.1-SNAPSHOT (compatibility: strict semantic versioning)
[info] Module api:1.2.1-SNAPSHOT has no dependency issues with version 1.2.0 (versionPolicyIntention is set to 'Compatibility.BinaryAndSourceCompatible')
[info] Module client:1.2.1-SNAPSHOT is binary and source compatible with version 1.2.0
```

Setting either version to `1.2.1`, compatibility to `BinaryCompatible` or adding versions with qualifier to `versionPolicyIgnoredInternalDependencyVersions` resolves this error.

What is strange to me is that version of `client` in error above is `1.2.0`, i.e. taken from previous artefacts.

**Comment by julienrf** [comment]
`versionPolicyCheck` checks that the dependencies of the current version of the module `client` don’t break the compatibility guarantees (as per `versionPolicyIntention`) with respect to the dependencies of the previous version of the module `client`, which in your case is the version `1.2.0`. Hence the message “Incompatibilities with dependencies of client:1.2.0”. The reported incompatibility is that the dependency to the module `api` changed from version `1.2.0` to version `1.2.1-SNAPSHOT`, and sbt-version-policy [does not know how to compare a stable version number with a pre-release version number](https://github.com/scalacenter/sbt-version-policy/blob/2f155c2cb57cce4de28645c1b1333fa1d7647fe5/sbt-version-policy/src/main/scala/sbtversionpolicy/DependencyCheckReport.scala#L173). That’s why changing the version to `1.2.1` does work.

Changing the compatibility intention to `BinaryCompatible` works because the check is slightly different: we [delegate to Coursier](https://github.com/scalacenter/sbt-version-policy/blob/2f155c2cb57cce4de28645c1b1333fa1d7647fe5/sbt-version-policy/src/main/scala/sbtversionpolicy/DependencyCheckReport.scala#L145), whose [algorithm](https://github.com/coursier/versions/blob/03029ca60dd7e3a0634dbc3aad27693b2eb3644d/versions/shared/src/main/scala/coursier/version/VersionCompatibility.scala#L78-L92) seems to support the `-SNAPSHOT` suffix. I am tempted to say that we should probably align both behaviors (with `BinaryCompatible` and `BinaryAndSourceCompatible`), and probably it makes sense to just ignore the `-SNAPSHOT` part (or any pre-release identifier or metadata part).

What do you think?

**Comment by seigert** [comment]
Sorry for the long wait, I'm in full agreement with your proposed changes. I'll try to find time to implement it.
