### ISSUE TITLE
versionScheme setting

### ISSUE THREAD

**Issue by eed3si9n** [scalacenter/sbt-version-policy#26]
Ref https://github.com/sbt/sbt/issues/5710

Does it make sense for the default use case to use

```scala
ThisBuild / versionScheme := Some(...)
```

as opposed to 

```scala
compatibilityRules += "org.scala-lang.modules" %% "scala-xml" % "..."
```

?

We can derive the `compatibiltyRules` automatically from `projectID`.

**Comment by julienrf** [comment]
`versionScheme` is for libraries, whereas `compatibilityRules` is for *users* of libraries. So, in the example given in the README, if we use `scala-xml` we have a way to specify that its versioning scheme is `"semver"` so that the `compatibilityCheck` task fails if we bump the major version of our dependency to `scala-xml` without also bumping the major version of our library.

**Comment by eed3si9n** [comment]
oh I see. I totally did not understand that.

Could we rename the key to `dependencyCompatiblityRules`? It's a bit long, but I think it would be clearer.

**Comment by julienrf** [comment]
There is a convention that keys are all prefixed the sbt plugin name (e.g., `mimaPreviousArtifacts`, `mimaBinaryReport`, etc.), so maybe we want to name it `compatibilityDependencyRules`? Note that this key is (currently) reused by sbt-eviction-rules to fix the eviction warnings.

Also, please note that this key should not be needed anymore when library authors switch to sbt 1.4.0 and use `versionScheme := Some("early-semver")` because then the library resolution system will be able to find the information directly in the artifacts metadata.

**Comment by eed3si9n** [comment]
I think it's ok to break from the prefix best practices when it makes sense since the purpose is to mostly avoid key conflict with other plugins. For now I can change to `compatibilityDependencyRules`.

**Comment by eed3si9n** [comment]
Getting back to the `versionScheme`, I think we might want to change the behavior of the compatibility check depending on the version scheme chosen by the build user.

| versionScheme | 0.1.0 vs 0.1.1              | 0.1.0 vs 0.2.0         | 1.0.0 vs 1.0.1                  | 1.0.0 vs 1.1.0              | 1.0.0 vs 2.0.0         |
|---------------|-----------------------------|------------------------|---------------------------------|-----------------------------|------------------------|
| EarlySemVer   | bincompat<br>("minor bump") | none<br>("major bump") | source + bincompat<br>("patch") | bincompat<br>("minor bump") | none<br>("major bump") |
| PackVer       | bincompat<br>("minor bump") | none<br>("major bump") | source + bincompat<br>("patch") | none<br>("major bump")      | none<br>("major bump") |
| SemVerSpec    | none<br>("dev")             | none<br>("dev")        | source + bincompat<br>("patch") | bincompat<br>("minor bump") | none<br>("major bump") |

**Comment by julienrf** [comment]
> Getting back to the `versionScheme`, I think we might want to change the behavior of the compatibility check depending on the version scheme chosen by the build user.

Could this be left for a second round? I guess a first version could just set `versionScheme := Some("early-semver")` and handle only this case.

**Comment by eed3si9n** [comment]
Yup. I introduced the notion of `VersionChange` in #31 for forward compatibility checks but hardcoded the scheme to Early Semver. Introducing `ThisBuild / versionScheme` support on top of that was very small change - https://github.com/scalacenter/sbt-compatibility/pull/32
